###
GET http://localhost:3000/

###
GET http://localhost30000/api/character/:id/items



###
GET http://localhost:3000/api/skills/
###
POST http://localhost:3000/api/skills/
Content-Type: application/json

###
GET http://localhost:3000/api/items


###
POST http://localhost:3000/api/items
Content-Type: application/json

{ "name": "Support de moniteur", "effect": "augmenterPrecision" }

###
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "name": "Le Voile des Étoiles Éteintes",
  "xpReward": 5000,
  "moneyReward": 5500
}

###
POST http://localhost:3000/api/quests
Content-Type: application/json

###
DELETE http://localhost:3000/api/items/:id

###
GET http://localhost:3000/api/characters/1/items 
###