###
GET http://localhost:3000/

###
GET http://localhost:3000/api/characters/

###
POST http://localhost:3000/api/competences/ 
Content-Type: application/json


{
    "name": "PHP"
}
###
POST http://localhost:3000/api/items
Content-Type: application/json

{ "name": "Support de moniteur", "effect": "augmenterPrecision" }

###
GET http://localhost:3000/api/items

###
POST http://localhost:3000/api/quests
Content-Type: application/json

{
  "name": "Le Voile des Étoiles Éteintes",
  "xpReward": 5000,
  "moneyReward": 5500
}

###
GET http://localhost:3000/api/quests

###
DELETE http://localhost:3000/api/items/3